trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline on
  paths:
    include:
      - myapp2/**

pool:
  vmImage: 'windows-latest'

stages:
  - stage: BUILD
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              cd myapp2
              npm install
              npm run build
            displayName: 'npm install and build'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            artifact: drop

          - task: AzureFunctionApp@1
            displayName: 'Azure Functions App Deploy: $(FUNCTION_APP_NAME)'
            inputs:
              azureSubscription: 'Free Trial(1)(3e3c63cc-eef2-4386-9f86-ea6a77a47519)'
              appType: 'functionApp'
              appName: 'forpathtesting'
              package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              deploymentMethod: 'auto'
