trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline on
  paths:
    include:
      - myapp2/**

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      cd myapp2
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/myapp2/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/myapp2_build_$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive build artifacts'

  - task: AzureFunctionApp@2
    inputs:
      connectedServiceNameARM: 'Free Trial(3e3c63cc-eef2-4386-9f86-ea6a77a47519)'
      appType: 'functionApp'
      appName: 'forpathtesting'
      package: '$(Build.ArtifactStagingDirectory)/myapp2_build_$(Build.BuildId).zip'
      deploymentMethod: 'auto'
