trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline on
  paths:
    include:
      - myapp/**

pool:
  vmImage: 'windows-latest'

stages:
  - stage: BUILD
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              cd myapp2
              npm install
              npm run build
            displayName: 'npm install and build'

          # Deploy to Azure Static Web App
          - task: AzureStaticWebApp@0
            inputs:
              app_location: 'myapp2'  # The folder where your app is located
              output_location: 'build'  # The folder where the build output is located
              azure_static_web_apps_api_token: 'a91adb19a7e1f7d199b456f26d55e97080daea25e97e769c527383b6385cfc1d5-46c3b62b-5df6-43ab-bca4-a0cdc8a2b3c300f398616'
            displayName: 'Deploy to Azure Static Web App'
